name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    # ----------------------------
    # Backend Setup
    # ----------------------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Start Flask backend
      run: |
        cd backend
        python app.py > ../backend.log 2>&1 &
        sleep 3

    - name: Wait for Flask backend
      run: |
        for i in {1..40}; do
          if curl -s http://localhost:5000/ > /dev/null; then
            echo "Backend started!"
            exit 0
          fi
          echo "Waiting backend ($i)..."
          sleep 1
        done
        echo "Backend failed"
        cat backend.log
        exit 1

    # ----------------------------
    # Frontend Setup
    # ----------------------------
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install frontend deps
      run: |
        npm install -g serve
        cd task-ui
        npm install

    - name: Start frontend
      run: |
        cd task-ui
        serve -l 3000 . > ../frontend.log 2>&1 &
        sleep 2

    # ----------------------------
    # Playwright
    # ----------------------------
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
